language: ruby
rvm:
- 2.1.2
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push
branches:
  only:
  - master
env:
  global:
  - secure: qHwZmkqO1sOuxaLxRTsTBpP6RR0Ir550Ta+H4sLL5tB3ZlUglYmhiLtLlu5VtKaAUyTGDPObASuWZI/RMEuupBrQpyU2OM07yCoEHGRjFrrMZAcUXavrtUmiD+ntuSXA53U06+wsbp8s4w+LOyfGPpmzwQjPbqCCO8pGPHIJ9wE=
  - secure: J7+8DS7vNl/eeFlj2a6iB8u+a7qyt7khffyLeIyAkOmCdQBhUthim8NUVGm3zsMlpM6QPvk8JULhrc0JZFeJFgzWVgVyRXLVr6Q93oi4qGNYtLMsebwSypySAe4SvqMfS9AeA69TDe9n17iNCKTig+s04vkHMa2kJo+iylH/Sv8=
