url: http://www.international-criminal-justice-today.org/
sitename: 'International Criminal Justice Today'
description: 'ABA Center for Human Rights'

default_author: "ABA-ICC Project Staff"

#Jekyll Options
# if using more than one Jekyll instance on your local machine
port: 8088

include: ['_pages']
# relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'content-list.yaml']


image_path: '/assets/img/'
# gems:
  #- jekyll-sitemap

# dev options (true/false)
# if site is in production, 'production: true'
production: false
include_addthis_sharing: true
bust_css_cache: true

# options (data)
google_analytics_id: UA-xxxxxxxx-X
disqus_id:
addthis_id: "ra-54201ddc58a3be09"
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:

sass:
    style: :compressed
    sass_dir: assets/css/_sass

# source: content
# TODO: Set default layouts for posts, pages, and arguendo, and ipsos

collections:
 arguendo:
  collection_name: "Arguendo"
  output: true
  description: "A regular online roundtable where experts from different perspectives discuss and debate a pressing issue in international criminal justice."
  main_page_link: "/arguendo/"
  permalink: /:collection/:path/
  class: arguendo
 ipsos:
   collection_name: "Ipsos Polling Data"
   main_page_link: "/ipsos/"
   output: true
   permalink: /:collection/:path/

defaults:
  -
   scope:
    path: ''
   values:
    layout: post
  -
   scope:
    path: "arguendo/article"
    type: arguendo
   values:
    layout: article-arguendo
  -
   scope:
    path: "arguendo/question"
    type: arguendo
   values:
    layout: arguendo

prose:
  siteurl: 'http://www.international-criminal-justice-today.org/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: '/assets/img'
  ignore:
    - index.md
    - _config.yml
    - _layouts
    - _includes
    - assets
    - api
    - _ipsos
    - .bowerrc
    - .gitignore
    - .travis.yml
    - 404.html
    - CNAME
    - license.md
    - _flags.html
    - atom.xml
    - bower.json
    - favicon.ico
    - gemfile
    - Gemfile.lock
    - readme.md
    - robots.txt
    - _pages/arguendo.md
    - _pages/contributing-authors.md
    - _pages/mailing-list.md
  metadata:
    _posts:
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
          placeholder: 'Put your title here'
      - name: "category"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "News"
              value: "news"
            - name: "Event"
              value: "event"
            - name: "Opinion"
              value: "opinion"
            - name: "Ipsos"
              value: "ipsos"
      - name: "pull_quote"
        field:
          element: 'text'
          label: "Pull Quote"
          placeholder: "large quote, top left"
      - name: "pull_quote_atribution"
        field:
          element: 'text'
          label: "Pull Quote Atribution"
          placeholder: "below large quote, top left"
      - name: "video"
        field:
          element: "text"
          label: "Video"
          placeholder: "specify a video ID from Youtube - will play in top section"
      - name: 'published'
        field:
          element: 'hidden'
          value: 'true'
    _pages:
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
          placeholder: 'Title'
          value: 'Title'
      - name: 'permalink'
        field:
          element: 'text'
          label: 'Link'
          help: '/page-name/'
      - name: 'include'
        field:
          label: 'Include Snippet'
          element: 'text'
          help: 'for developer use only'
          label: 'snippet'