url: http://www.international-criminal-justice-today.org/
sitename: 'International Criminal Justice Today'
description: 'ABA Center for Human Rights'

#Jekyll Options
# if using more than one Jekyll instance on your local machine
port: 4049

include: ['_pages']
# relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'content-list.yaml']

# gems:
  #- jekyll-sitemap

# dev options (true/false)
# if site is in production, 'production: true'
production: false
include_addthis_sharing: true
bust_css_cache: true

# options (data)
google_analytics_id: UA-xxxxxxxx-X
disqus_id:
addthis_id: "ra-XXXXXXXXX"
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:

sass:
    style: :compressed
    sass_dir: assets/css/_sass

# source: content

collections:
 arguendo:
  collection_name: "Arguendo"
  output: true
  description: "Experts debate issues of the day on International Criminal Justice"
  main_page_link: "/arguendo/"
  permalink: /:collection/:path/
  class: arguendo
 ipsos:
   collection_name: "Ipsos Polling Data"
   main_page_link: "/ipsos/"
   output: true
   permalink: /:collection/:path/

defaults:
  -
   scope:
    path: ''
    type: page
   values:
    layout: page
  -
   scope:
    path: "arguendo/article"
    type: arguendo
   values:
    layout: article-arguendo
  -
   scope:
    path: "arguendo/question"
    type: arguendo
   values:
    layout: arguendo

