---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
collections:
- path: _posts
  label: Posts
  create: all
- path: _arguendo
  label: Arguendo
  create: all
- path: _arguendo-questions
  label: Arguendo-questions
  create: all
- path: _contributors
  label: Contributors
  create: all
- path: _events
  label: Events
  create: all
- path: _landing_pages
  label: Landing_pages
  create: all
- path: _news
  label: News
  create: all
- path: _opinion
  label: Opinion
  create: all
- path: _polling-data
  label: Polling-data
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
