---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _arguendo
  label: Arguendo
  create: all
  match: "**/*"
- type: directory
  path: _arguendo-questions
  label: Arguendo-questions
  create: all
  match: "**/*"
- type: directory
  path: _contributors
  label: Contributors
  create: all
  match: "**/*"
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: _landing_pages
  label: Landing_pages
  create: all
  match: "**/*"
- type: directory
  path: _news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: _opinion
  label: Opinion
  create: all
  match: "**/*"
- type: directory
  path: _polling-data
  label: Polling-data
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
